version: "3.4"

services:
  presta:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
  database:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=presta
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"